### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mureni** [mureni/charlies4#1]
- [ ] Create ngram (1, 2, 3, 4), token, tag, url, madlibs, database structures
    - [ ] trigram current: [token1, token2, token3], freq
    - [ ] trigram prev: [prev, token1, token2], freq, sum
    - [ ] trigram next: [token2, token3, next], freq, sum
- [ ] Research entropy algorithms for surprise vs standard random weighted
- [ ] Create REST API
- [ ] Tokenize and normalize and tag input
    - [ ] Create Middleware parsing (urls, emojis, discord users, matrix users, wtf Wikipedia, punctuation, subj/obj swapping, q/a, etc) 
- [ ] Create REST API Explorer
- [ ] Create test data and tests
- [ ] Integrate with bot framework
